mongoeat_vote:
    resource: "@MongoeatVoteBundle/Controller/"
    type:     annotation
    prefix:   /

mongoeat_restaurant:
    resource: "@MongoeatRestaurantBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxTumblrBundle:
    resource: "@MongoboxTumblrBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: MongoboxCoreBundle:Wall:index }

MongoboxJukeboxBundle:
    resource: "@MongoboxJukeboxBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxCoreBundle:
    resource: "@MongoboxCoreBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxUsersBundle:
    resource: "@MongoboxUsersBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxGroupBundle:
    resource: "@MongoboxGroupBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxStatisticsBundle:
    resource: "@MongoboxStatisticsBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_login_check:
    pattern: /login_check
    requirements: {_method : POST }

_logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine
